/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more
 letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

//solution
class Solution {
public:
    /*char findTheDifference(string s, string t) {
        int freq1[26]={0};
        int freq2[26]={0};
        for(auto c : s)
            freq1[c-'a']++;
        for(auto c : t)
            freq2[c-'a']++;
        for(int i = 0; i < 26;i++){
            if(freq1[i] != freq2[i])
                return i+'a';
        }
        return '\0';
    }*/
    char findTheDifference(string s, string t) {
        char ch = 0;
        for(auto c : s)
            ch = ch ^ c;
        for(auto c : t)
            ch = ch ^ c;
        return ch;
    }
};